export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_CHARACTERS_ERROR = 'GET_CHARACTERS_ERROR';
export const GET_CHARACTERS_FILTER = 'GET_CHARACTERS_FILTER';

export const GET_ONE_CHARACTER = 'GET_ONE_CHARACTER';
export const GET_ONE_CHARACTER_SUCCESS = 'GET_ONE_CHARACTER_SUCCESS';
export const GET_ONE_CHARACTER_ERROR = 'GET_ONE_CHARACTER_ERROR';